plant/cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  
      path('view_cart',views.view_cart,name='view_cart'),
      path('add_to_cart/<int:variant_id>/',views.add_to_cart,name='add_to_cart'),
      path('update_quantity', views.update_quantity, name='update_quantity'),
      path('remove_from_cart',views.remove_from_cart,name='remove_from_cart'),
      path('apply_coupon',views.apply_coupon,name='apply_coupon'),
      path('add_to_whishlist/<int:variant_id>/',views.add_to_whishlist,name='add_to_whishlist'),
      path('remove_wish/<int:variant_id>/',views.remove_wish,name='remove_wish'),
      path('view_wishlist',views. view_wishlist,name='view_wishlist'),
  


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plant/orders/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  
    path('checkout/<int:add_id>/',views.checkout,name='checkout'),
    path('placeorder/<int:add_id>/',views.placeorder,name='placeorder'),
    
    path('orders',views.orders, name='orders'),
    path('order-view/<int:order_id>/',views.order_view, name='order_view'),
    path('cancel_orderss/<int:order_id>/',views.cancel_orderss, name='cancel_orderss'),
    path('Return_orderss/<int:order_id>/',views.Return_orderss, name='Return_orderss'),
    path('initiate_payment',views.initiate_payment, name='initiate_payment'),
    path('online_payment_order/<int:add_id>/',views.online_payment_order,name='online_payment_order'),
    # path('invoice_download/<int:order_id>/',views.invoice_download, name='invoice_download'),
    path('invoice_download_start/<int:order_id>/',views.invoice_download_start, name='invoice_download_start'),
     


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plant/plant/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('',include('authenticate.urls')),
    path('',include('adminside.urls')),
    path('',include('userprofile.urls')),
    path('',include('cart.urls')),
    path('',include('orders.urls')),

   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plant/userprofile/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  
      path('profile_view',views.profile_view,name='profile_view'),
      path('add_address',views.add_address,name='add_address'),
      path('show_address',views.show_address,name='show_address'),
      path('edit_address/<int:address_id>',views.edit_address,name='edit_address'),
      path('order_edit_address/<int:address_id>',views.order_edit_address,name='order_edit_address'),
      path('order_address',views.order_address,name='order_address'),
      path('delete_address/<int:address_id>',views.delete_address,name='delete_address'),
      path('refer',views.refer,name='refer'),
      path('wallet',views.wallet,name='wallet'),
      path('change_password',views.change_password,name='change_password'),
      path('no_adress_add',views.no_adress_add,name='no_adress_add'),
  



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plant/orders/models.py
from datetime import timedelta, timezone
from django.db import models
from userprofile.models import *
from django.utils import timezone
from store.models import *


# Create your models here.

class Order(models.Model):
    PAYMENT_STATUS_CHOICES = [
        ('PENDING','pending'),
        ('PAID','paid'),
        ('CANCELLED','cancelled'),
        ('DELIVERED','Delivered'),
        ('SHIPPED','Shipped'),
        ('RETURNED','Returned'),
        ('ORDERED','Ordered'),
        ('COMPLETED','Completed')
    ]
    PAYMENT_METHOD_CHOICES = [
        ('RAZORPAY', 'razorpay'),
        ('CASH_ON_DELIVERY', 'Cash on Delivery'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(User_address, on_delete=models.CASCADE)
    total_price = models.FloatField(null=False)
    original_price = models.FloatField(null=True)
    coupon=models.FloatField(null=True)
    payment_status = models.CharField(max_length=25, choices=PAYMENT_STATUS_CHOICES, default='ordered')
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES)
    message = models.TextField(null=True)
    tracking_no = models.CharField(max_length=150,null=True)
    order_date = models.DateTimeField(default=timezone.now)
    delivery_date = models.DateTimeField(blank=True, null=True)
    razor_pay_order_id =models.CharField( max_length=150,null=True, blank=True)
    razor_pay_payment_id =models.CharField( max_length=150,null=True, blank=True)
    razor_pay_payment_signature =models.CharField( max_length=150,null=True, blank=True)


    def __str__(self):
        return f"{self.id, self.tracking_no}"
    def _str_(self):
        return f"{self.id}  {self.user.username}"

    def save(self, *args, **kwargs):
        if not self.order_date:
            self.order_date = timezone.now()  
        if not self.delivery_date:
            self.delivery_date = self.order_date + timedelta(hours=24)
        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariant, on_delete=models.CASCADE)
    price = models.FloatField(null=False)
    quantity = models.IntegerField(null=False)
    def __str__(self):
        return f"{self.order.id, self.order.tracking_no}"

plant/store/models.py
from decimal import Decimal
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category_images')
    bannerimage = models.ImageField(upload_to='category_images')
    slug = models.SlugField(blank=True, max_length=250, unique=True)
    discount =models.PositiveIntegerField( null=True,blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('cat',kwargs={'slug': self.slug})

    


    def __str__(self):
        return self.name

class Banner(models.Model):
    name = models.CharField(max_length=50)
    image=models.ImageField(upload_to='banner_images')

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=100)
    shortdescription = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    shortdescription = models.TextField()
    slug = models.SlugField(blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product_detail',kwargs={'slug': self.slug})

class Color(models.Model):
    color = models.CharField(max_length=15)

    def __str__(self):
        return self.color
class ProductVariant(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    model_name=models.CharField(max_length=250)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    store_price = models.DecimalField(max_digits=10,decimal_places=2)
    sale_price = models.DecimalField(max_digits=10,decimal_places=2)
    discount_percentage =models.PositiveIntegerField(null=True,blank=True)
    stock = models.PositiveIntegerField(default=0)
    slug = models.SlugField(blank=True,unique=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            print('------------>>>>>>>>>>><<<<<<<<<<<<---------------->>>>>>>>>>>>>><<<<<<<<<<<<<<<<')
            slug_str = f"{self.product.name} {self.color}"
            self.slug=slugify(slug_str)
        super().save(*args, **kwargs)

    def  __str__(self):
        return f"{self.product.name} - {self.color}"
    

    # def get_discounted_price(self):
    #     if self.discount_percentage is not None:
    #         discount= int(self.discount_percentage)
    #         print(f"Type of self.sale_price: {type(self.sale_price)}")
    #         print(f"Type of discount: {type(discount)}")
    #         self.sale_price = self.sale_price- (self.sale_price*discount)/100.0
    #         return self.sale_price
       
    #     return self.sale_price
    
    def get_discounted_price(self):
        category_discount= self.product.category.discount if self.product.category.discount else 0
        product_discount= self.discount_percentage if self.discount_percentage else 0 
        max_discount= max(category_discount,product_discount)
        discount = Decimal(max_discount)
        if discount > 0:
        # Calculate discounted price if there's any discount
          discounted_price = Decimal(self.sale_price) - (Decimal(self.sale_price) * discount) / 100
        else:
        # If there's no discount, then discounted_price is equal to the sale_price
          discounted_price = Decimal(self.sale_price)
        # return self.sale_price, max_discount
        discounted_price = Decimal(self.sale_price) - (Decimal(self.sale_price) * discount) / 100
        return discounted_price, max_discount
    

        # return Decimal(self.sale_price)
     
     
    # def save(self, *args, **kwargs):
    #     self.get_discounted_price()
    #     super(ProductVariant, self).save(*args, **kwargs)


    
class ProductImage(models.Model):
    variant = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/')

    def __str__(self):
        return f"Image for {self.variant.product.name} - {self.variant.color}"

plant/cart/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import *
from store.models import *
from userprofile.models import *
from django.views.decorators.cache import never_cache



def create_or_get_cart(request):
   
    if request.user.is_authenticated:
    # if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
    else:
        session_key = request.session.session_key
       
        if  session_key is None:
            request.session.save()
            session_key = request.session.session_key
           
        cart, _ = Cart.objects.get_or_create(user=None, session_key= session_key)

       
    return cart     


def add_to_cart(request, variant_id):
   
    variant = ProductVariant.objects.get(id=variant_id)
    discounted_price, _ = variant.get_discounted_price()

    cart  = create_or_get_cart(request)

    item, created = cart.cartitems_set.get_or_create(
        product=variant,
        defaults={'price': discounted_price, 'quantity': 1}
    )

    if not created:
        item.quantity += 1
        item.price = discounted_price * item.quantity
        item.save()

    return redirect('view_cart')

@never_cache
def view_cart(request):
   
   
    final_price=0
    cart= create_or_get_cart(request)
    total_price = cart.get_total_price()  # Calculate the new total price
    if total_price is None:
      total_price = Decimal(0)
      
    request.session['total'] = str(total_price)
    coupon = Decimal(request.session.get('coupon', '0'))
    if coupon>0:
        final_price=total_price-coupon
    else:
        final_price=total_price
    request.session['final'] = str(final_price)

   
    
   
    cart_items = cart.cartitems_set.all()
   
     
    discounted_price = 0  
    
   

    if cart_items:
   
     coupons = Coupon.objects.filter(is_active=True, minimum_order_amount__lte=total_price)
        

     context = {
            'cart': cart,
            'total_price': total_price,
            'discounted_price': discounted_price,
            
            'coupons': coupons,
            
     }

     return render(request, 'cart_view.html', context)
    else:
        return render(request, 'empty_cart.html')





          



def apply_coupon(request):
    
    cart = create_or_get_cart(request)

    cart_items = cart.cartitems_set.all()
   
    coupon_applied_total=0
    total_price = Decimal(request.session['total'])
    

    coupons = Coupon.objects.filter(is_active= True)    
    

    if request.method == 'POST':
       
        selected_coupon_code = request.POST.get('coupon_code')
        if not selected_coupon_code:
         return JsonResponse({
            'success': False,
            'message': 'No coupon selected.',
         })
       
        
        
        selected_coupon = Coupon.objects.get(code=selected_coupon_code)
        


        if selected_coupon_code:
           
            selected_coupon = get_object_or_404(Coupon, code=selected_coupon_code)
            if selected_coupon.minimum_order_amount <= total_price  :
               
               coupon_applied_total = total_price - selected_coupon.discount
               coupon_discount=total_price-coupon_applied_total
               request.session['coupon'] = str(coupon_discount)
               request.session['final'] = str(coupon_applied_total)
              
               return JsonResponse({
                    'success': True,
                    'coupon_code': selected_coupon_code,
                    'final_price': float(coupon_applied_total),
                    'coupon_discount': float(coupon_discount)

                })
            
            else:
              selected_coupon.discount=0
              selected_coupon_code= None
              return JsonResponse({
                    'success': False,
                    'message': 'Failed to apply coupon'
              })
    

    else:
    # If not a POST request, return available coupons
      coupons = Coupon.objects.filter(is_active=True, minimum_order_amount__lte=total_price)
      coupons_list = list(coupons.values())  # Convert QuerySet to list of dictionaries
      return JsonResponse(coupons_list, safe=False)        
    # return render(request, 'cart_view.html', context)

    
   


    
def remove_from_cart(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
       
        cart_item = CartItems.objects.get(id=item_id)
        cart_item.delete()

        return redirect('view_cart')

    # return render(request, 'cart_view.html')
    return redirect('view_cart')


    

def update_quantity(request):
    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        product_id = request.POST.get('product_id')
        quantity = request.POST.get('quantity')
        
        product = CartItems.objects.get(id=product_id)
        product.quantity = quantity
        product.price = product.discounted_item_price 
       

        product.save()

        cart = product.cart  # Retrieve the cart object
        total_price = cart.get_total_price()  # Calculate the new total price
        request.session['total'] = str(total_price)
        
        final_price=total_price
        request.session['final'] = str(final_price)
        coupon=0
        request.session['coupon'] = str(coupon)
        
        

        response_data = {
            'success': True,
            'message': 'Quantity updated successfully!',
            'price': str(product.price),
            'quantity': str(product.quantity),
            'total_price': str(total_price),
            'coupon': str(coupon),
        }

        return JsonResponse(response_data)
    
    response_data = {
        'success': False,
        'message': 'Invalid request',
    }
    
    return JsonResponse(response_data, status=400)



def add_to_whishlist(request, variant_id):
      
      if not request.user.is_authenticated:
          
          return redirect('signin')
      variant = ProductVariant.objects.get(id=variant_id)

      wishlist, created = Wishlist.objects.get_or_create(user=request.user)
      item = wishlist.wishlistitem_set.filter(product=variant)

      if item.exists():
    
          return redirect('view_wishlist')
      else:
           WishlistItem.objects.create(wishlist = wishlist, product=variant)
           return redirect('view_wishlist')

def remove_wish(request, variant_id):
    variant = ProductVariant.objects.get(id=variant_id)
    wishlist = get_object_or_404(Wishlist,user=request.user)
    item = wishlist.wishlistitem_set.filter(product=variant)

    if item.exists():
      item.delete()

    return redirect('view_wishlist')


    

def view_wishlist(request):
    wishlist= get_object_or_404(Wishlist, user=request.user)
    user_products = CartItems.objects.filter(cart__user= request.user).values_list('product__id' , flat=True)
    items= WishlistItem.objects.filter( wishlist= wishlist)
   
    return render(request, 'view_wishlist.html', {'wishlist': wishlist, 'items': items, 'user_products':user_products})



   

plant/templates/admin_addproduct.html
{% extends 'admin_base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <h1>Add Product Variant</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Product Name</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="shortdescription">Short description</label>
                    <input type="text" class="form-control" id="shortdescription" name="shortdescription" required>
                </div>
                <div class="form-group">
                    <label for="created_at">Created At</label>
                    <input type="datetime-local" class="form-control" id="created_at" name="created_at" required>
                </div>
                <div class="form-group">
                    <label for="updated_at">Updated At</label>
                    <input type="datetime-local" class="form-control" id="updated_at" name="updated_at" required>
                </div>
                <div class="form-group">
                    <label for="category">Category</label>
                    <select class="form-control" id="category" name="category" required>
                        <option value="" disabled selected>Select a category</option>
                        {% for category in cat %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                
                <div class="form-group">
                    <label for="model_name">Model Name</label>
                    <input type="text" class="form-control" id="model_name" name="model_name" required>
                </div>
                
                <div class="form-group">
                    <label for="color">Color variant</label>
                    <select class="form-control" id="color" name="color" required>
                        <option value="" disabled selected>Select a color</option>
                        {% for color in color %}
                            <option value="{{ color.color }}">{{ color.color }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="store_price">Store Price</label>
                    <input type="number" class="form-control" id="store_price" name="store_price" required>
                </div>
                <div class="form-group">
                    <label for="sale_price">Sale Price</label>
                    <input type="number" class="form-control" id="sale_price" name="sale_price" required>
                </div>
                <div class="form-group">
                    <label for="sale_price">Discount Percentage</label>
                    <input type="number" class="form-control" id="discount" name="discount" required>
                </div>
                <div class="form-group">
                    <label for="stock">Stock</label>
                    <input type="number" class="form-control" id="stock" name="stock" required>
                </div>
                
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="images">Variant Images</label>
                    <input type="file" class="form-control-file" id="images" name="images" multiple required>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">SUBMIT</button>
    </form>
</div>
{% endblock %}

plant/templates/admin_products.html
{% extends 'admin_base.html' %}
{% load static %}

{% block body %}

<div class="container-fluid" style="margin-top: 30px; margin-bottom: 20px;">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <h5 class="cat-list-title fw-semibold mb-4 text-center">PRODUCTS</h5>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">No.</th>
                                <th scope="col" class="text-center">Name</th>
                                <th scope="col" class="text-center">Category</th>
                                <th scope="col" class="text-center">Image</th>
                                <th scope="col" class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for  product in products %}
                            {% with variant=product.productvariant_set.all|random %}
                            <tr>
                                <th scope="row" class="text-center">{{ product.id }}</th>
                                <td class="text-center">{{ product.name }}</td>
                                <td class="text-center">{{ product.category.name }}</td>

                                <td class="text-center">
                                    <img src="{{ variant.images.first.image.url }}" alt="{{ product.name }} Image" width="80"
                                        height="70">
                                </td>
                               
                                <td class="text-center">
                                    <div class="d-flex justify-content-center">
                                        <div class="mb-2">
                                            <a href="{% url 'admin_varients' product.id %}" class="btn btn-warning btn-sm">View</a>

                                        </div>
                                        {% if product.is_active %}
                                        <div class="mb-2">
                                            <a href="" class="btn btn-danger btn-sm">DISABLE</a>
                                        </div>
                                        {% else %}
                                        <div class="mb-2">
                                            <a href="" class="btn btn-success btn-sm">ENABLE</a>
                                        </div>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                            {% endwith %}
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

plant/templates/admin_productvarients.html
{% extends 'admin_base.html' %}
{% load static %}

{% block body %}

<div class="container-fluid" style="margin-top: 130px; margin-bottom: 20px;">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <h5 class="cat-list-title fw-semibold mb-4 text-center">PRODUCT VARIANTS</h5>
                    <div>
                        <a href="{% url 'admin_addvarients' product.id %}" class="btn btn-success mb-4">Add Variant</a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">No.</th>
                                <th scope="col" class="text-center">Name</th>
                                <th scope="col" class="text-center">Sale Price</th>
                                <th scope="col" class="text-center">Discount</th>
                                <th scope="col" class="text-center">Variant</th>
                                <th scope="col" class="text-center">Image</th>
                                <th scope="col" class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for variant in varients %}
                                <tr>
                                    <th scope="row" class="text-center">{{ variant.id }}</th>
                                    <td class="text-center">{{ product.name }}</td>
                                    <td class="text-center">{{ variant.sale_price }}</td>
                                    <td class="text-center">{{ variant.discount_percentage }}</td>
                                    <td class="text-center">{{ variant.color }}</td>

                                    <td class="text-center">
                                        <img src="{{ variant.images.first.image.url }}" alt="{{ product.name }} Image" width="80" height="70">
                                    </td>
                                   
                                    <td class="text-center">
                                        <div class="d-flex justify-content-center">
                                            <div class="mb-2">
                                                <a href="{% url 'admin_editvarients' id=variant.id %}" class="btn btn-warning btn-sm">Edit</a>
                                            </div>
                                            {% if variant.is_active %}
                                                <div class="mb-2">
                                                    <a href="{% url 'admin_disablevarients' id=variant.id %}" class="btn btn-danger btn-sm">DISABLE</a>
                                                </div>
                                            {% else %}
                                                <div class="mb-2">
                                                    <a href="{% url 'admin_enablevarients' id=variant.id %}" class="btn btn-success btn-sm">ENABLE</a>
                                                </div>
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

plant/templates/checkout.html
{% extends 'base.html' %}

{% block body %}
{% load static %}

<!-- Shopping Cart -->
<br>

<form class="bg0 p-t-75 p-b-85">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-auto mb-4">
                <div class="card">
                    <div class="card-header">
                        Selected Address
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ user_address.first_name }} {{ user_address.last_name }}</h5>
                        <p class="card-text">{{ user_address.email }}</p>
                        <p class="card-text">
                            {{ user_address.address_line_1 }}<br>
                            {{ user_address.city }}, {{ user_address.state }},<br>
                            {{ user_address.country }}, {{ user_address.postal_code }}
                        </p>
                        <p class="card-text">Ph: {{ user_address.phone_number }}</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-10 col-lg-7 col-xl-5 m-auto mb-4">
                <div class="card p-4">
                    <h4 class="m-0 pb-3">
                        Cart Totals
                    </h4>

                    <div class="d-flex justify-content-between border-bottom pb-2">
                        <span class="text-muted">Subtotal:</span>
                        <span class="font-weight-bold">{{ total_price }}</span>
                    </div>

                    <div class="d-flex justify-content-between border-bottom py-2">
                        <span class="text-muted">Shipping charge:</span>

                        {% if carts.get_total_price >= 500 %}
                        <span class="font-weight-bold" style="color: green;">Free Delivery</span>
                        {% else %}
                       
                        <span class="font-weight-bold">Rs 40 </span> 
                        
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-between pt-3">
                        <span class="text-dark font-weight-bold">Total:</span>
                        <span class="font-weight-bold">{{ total_price_delivery }}</span>
                    </div>

                    <div class="row pt-4">
                        <div class="col">
                            <a href="{% url 'placeorder' user_address.id %}" class="btn btn-primary btn-block" style="text-decoration: none;">
                                Cash on Delivery
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

plant/templates/confirmEmail.html
{% autoescape off %}
Hi {{ user.username }},

Welcome to eshop
Thank you for visiting our website
Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape%}